redis:
  uri: redis://localhost:6379
  #uris: # To use a cluster.
  # - redis://redis-1:6379
  # - redis://redis-2:6379
  io-thread-pool-size: 5
  computation-thread-pool-size: 4
  client-name: "factory"